import stim
import sys

stabilizers_str = [
"XXIIXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIXXIIXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIXXIIXXIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIXXIIXXIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIXXIIXXIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXIIXXIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXIIXXI", 
"XIXIXIXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIXIXIXIXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIXIXIXIXIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIXIXIXIXIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIXIXIXIXIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXIXIXIXIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXIXIXIX", 
"IIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXX", 
"ZZIIZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIZZIIZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIZZIIZZIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIZZIIZZIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIZZIIZZIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZIIZZIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZIIZZI", 
"ZIZIZIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIZIZIZIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIZIZIZIZIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIZIZIZIZIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIZIZIZIZIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZIZIZIZIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZIZIZIZ", 
"IIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIII", 
"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZ", 
"XXXIIIIXXXIIIIIIIIIIIIIIIIIIXXXIIIIXXXIIIIIIIIIII", 
"XXXIIIIIIIIIIIXXXIIIIIIIIIIIXXXIIIIIIIIIIIXXXIIII", 
"IIIIIIIIIIIIIIIIIIIIIXXXIIIIXXXIIIIXXXIIIIXXXIIII", 
"ZZZIIIIZZZIIIIIIIIIIIIIIIIIIZZZIIIIZZZIIIIIIIIIII", 
"ZZZIIIIIIIIIIIZZZIIIIIIIIIIIZZZIIIIIIIIIIIZZZIIII", 
"IIIIIIIIIIIIIIIIIIIIIZZZIIIIZZZIIIIZZZIIIIZZZIIII"
]

try:
    # Build tableau from ALL stabilizers
    # If they are dependent but consistent, allow_underconstrained=True should work fine.
    # It will pick a basis.
    
    # Check consistency?
    # No direct method, but from_stabilizers raises if inconsistent.
    
    tableau = stim.Tableau.from_stabilizers([stim.PauliString(s) for s in stabilizers_str], allow_underconstrained=True)
    
    # Check if the generated tableau stabilizes ALL of them.
    # If some are redundant, they might not be in the tableau's Z-generators explicitly,
    # but they should be in the group generated by them.
    # However, `check_stabilizers_tool` tests if the state |psi> = U|0> is a +1 eigenstate.
    # If S is in the group, it should be.
    # Unless there is a sign issue.
    
    # Let's check each stabilizer against the tableau.
    t_inv = tableau.inverse()
    
    failed_indices = []
    
    for i, s_str in enumerate(stabilizers_str):
        s = stim.PauliString(s_str)
        # Calculate t_inv * s * t_inv^-1 (or similar)
        # Actually t_inv(s) applies the inverse tableau operation to s.
        # This maps the stabilizer from the state basis to the |0> basis.
        # Ideally, it should map to +Z_k or a product of +Z_k's.
        # If it maps to something containing X or Y, then it's not stabilized by |0>.
        # If it maps to -Z..., then it's a -1 eigenstate.
        
        mapped = t_inv(s)
        
        m_str = str(mapped)
        
        # Check if it has X or Y
        has_xy = False
        for c in m_str:
            if c == 'X' or c == 'Y':
                has_xy = True
                break
        
        sign = m_str.startswith('-') or m_str.startswith('!-') # !- is not standard stim output for PauliString but checking just in case
        
        if has_xy:
            print(f"Stabilizer {i} maps to non-Z: {m_str}")
            failed_indices.append(i)
        elif sign:
            print(f"Stabilizer {i} maps to negative Z: {m_str}")
            failed_indices.append(i)
        else:
            # print(f"Stabilizer {i} OK: {m_str}")
            pass

    print(f"Failed indices count: {len(failed_indices)}")
    if len(failed_indices) > 0:
        print(f"Failed indices: {failed_indices}")

except Exception as e:
    print(f"Exception: {e}")
