import stim

# Generators
g0 = stim.PauliString("XZZXI")
g1 = stim.PauliString("IXZZX")
g2 = stim.PauliString("XIXZZ")
g3 = stim.PauliString("ZXIXZ")
stabs = [g0, g1, g2, g3]

# My logical X from the circuit
lx_circuit = stim.PauliString("_ZXZ_") # Ignoring sign for now
# The canonical logical X
lx_canonical = stim.PauliString("XXXXX")

# Check if lx_circuit * lx_canonical is in the stabilizer group
prod = lx_circuit * lx_canonical
print(f"Product: {prod}")

# Check if product is generated by stabs
# We can do this by Gaussian elimination.
# Or just brute force check since group size is small (16).
# But checking 16 elements is easy.

import itertools
found = False
for c in itertools.product([0, 1], repeat=4):
    s = stim.PauliString("IIIII")
    if c[0]: s *= g0
    if c[1]: s *= g1
    if c[2]: s *= g2
    if c[3]: s *= g3
    
    # Check + and -
    if s == prod or s == -prod:
        print(f"Found match! Product is equivalent to stabilizer combination {c}")
        found = True
        break

if not found:
    print("Product is NOT in stabilizer group. They are different logical operators!")
