import stim

def verify_local():
    # Read stabilizers
    with open("stabilizers_161.txt", "r") as f:
        stabilizers_str = [line.strip() for line in f if line.strip()]
    
    # Read circuit
    with open("circuit_161.stim", "r") as f:
        circuit_str = f.read()
        
    circuit = stim.Circuit(circuit_str)
    stabilizers = [stim.PauliString(s) for s in stabilizers_str]
    
    print(f"Circuit instructions: {len(circuit)}")
    
    # Check if the circuit prepares the state
    # The circuit U prepares |psi> = U|0>.
    # |psi> should be stabilized by S_i.
    # So U|0> is stabilized by S_i.
    # Equivalently, |0> is stabilized by U^{-1} S_i U.
    # Since |0> is stabilized by Z operators, U^{-1} S_i U should be a Z-only operator?
    # No, |0> is stabilized by Z_0, Z_1... and combinations.
    # It must be that U^{-1} S_i U |0> = |0>.
    # Which means U^{-1} S_i U must be in the stabilizer group of |0> (generated by Zs).
    # So U^{-1} S_i U must commute with all Zs? No, it must BE a product of Zs.
    
    # Let's use TableauSimulator to check.
    sim = stim.TableauSimulator()
    sim.do(circuit)
    
    # Now check if the state is stabilized by each S_i
    all_good = True
    for i, s in enumerate(stabilizers):
        # measure_expectation returns the expectation value of the observable.
        # For a stabilizer state, it should be +1 or -1.
        # We want +1.
        ex = sim.peek_observable_expectation(s)
        if ex != 1:
            print(f"Stabilizer {i} failed: expectation {ex}")
            all_good = False
            break
            
    if all_good:
        print("All stabilizers preserved!")
    else:
        print("Some stabilizers failed.")

if __name__ == "__main__":
    verify_local()
