import stim
import sys

def verify():
    with open('stabilizers_105_v2.txt', 'r') as f:
        stabilizers = [l.strip() for l in f if l.strip()]
    
    with open('circuit_105_v2.stim', 'r') as f:
        circuit_text = f.read()
    
    circuit = stim.Circuit(circuit_text)
    tableau = circuit.to_tableau()
    
    # Check if the state stabilized by the tableau satisfies the target stabilizers.
    # The tableau T represents the map U such that state = U|0>.
    # A stabilizer S stabilizes U|0> iff U_dagger S U stabilizes |0>.
    # U_dagger S U is the result of feeding S backward through the circuit,
    # or equivalently feeding S through the inverse tableau.
    # If S stabilizes the state, then T^-1(S) should be a Z-type Pauli string (modulo sign?).
    # Actually, T|0> is stabilized by Z_i for all i.
    # So we need S to be in the group generated by {T(Z_i)}.
    
    # Alternatively:
    # Simulating the circuit on |0> states and checking expectation values.
    # Stim has `peek_observable_expectation` but that is for a simulator.
    
    # Let's use tableau inverse method.
    inv_tableau = tableau.inverse()
    
    all_good = True
    for s_str in stabilizers:
        s = stim.PauliString(s_str)
        mapped = inv_tableau(s)
        # mapped should be a product of Z operators with +1 phase.
        # i.e., it should consist only of I and Z, and have sign +1.
        
        # Check if it has X or Y components
        is_z_type = True
        for p in mapped: # iterating gives 0,1,2,3 (I,X,Y,Z)
            if p == 1 or p == 2: # X or Y
                is_z_type = False
                break
        
        if not is_z_type:
            print(f"FAIL: {s_str} mapped to {mapped} (not Z-type)")
            all_good = False
        elif mapped.sign != +1:
            print(f"FAIL: {s_str} mapped to {mapped} (sign is not +1)")
            all_good = False
            
    if all_good:
        print("SUCCESS: All stabilizers preserved.")
    else:
        print("FAILURE: Some stabilizers not preserved.")

if __name__ == "__main__":
    verify()
