import stim

# Load baseline
with open("baseline.stim") as f:
    baseline = stim.Circuit(f.read())

# Get stabilizers of the state U|0>
# The stabilizers are U Z_i U^dag.
# We can get them by applying the tableau to Z_i.
t = baseline.to_tableau()

print("Stabilizers from baseline (U Z_i U^dag):")
output_stabilizers = []
for k in range(len(t)):
    # t.z_output(k) returns the Pauli string for U Z_k U^dag
    # But wait, does t.z_output(k) correspond to the kth stabilizer generator?
    # Yes, it is the image of Z_k.
    s = t.z_output(k)
    output_stabilizers.append(str(s))
    # print(f"{k}: {s}")

# Load target stabilizers
with open("target_stabilizers.txt") as f:
    targets = [line.strip() for line in f if line.strip()]

print(f"\nNumber of baseline stabilizers: {len(output_stabilizers)}")
print(f"Number of target stabilizers: {len(targets)}")

# Check if targets are in the baseline stabilizers (or generated by them)
# Since the baseline stabilizers form a basis for the stabilizer group of the state,
# every target stabilizer must be in the group generated by output_stabilizers.
# We can check this by seeing if the target stabilizer commutes with all output stabilizers?
# No, that just means it's in the normalizer.
# To be in the stabilizer group, it must be formed by product of generators.
# Simpler: check if baseline preserves them (we already did that and it said yes).

# But let's see if the LIST of targets matches any subset of the baseline stabilizers.
matches = 0
for t_str in targets:
    if t_str in output_stabilizers:
        matches += 1
    elif "-" + t_str in output_stabilizers:
        matches += 1
        print(f"Found match with sign flip: {t_str}")
        
print(f"Direct matches (string equality) between targets and baseline generators: {matches}/{len(targets)}")

# Maybe print the first few to compare visually
print("\nFirst 5 targets:")
for i in range(5):
    print(targets[i])

print("\nFirst 5 baseline stabilizers:")
for i in range(5):
    print(output_stabilizers[i])
