import stim

stabilizers = [
    "IIIIIXIIIXIXXIIII",
    "IIIIIIIIXIXIIXIXI",
    "IIIXIIIXIIIIIIXIX",
    "IIXIIIXIIIIIIIXIX",
    "IIIIXXXXXIXXIIIIX",
    "IXIIXIIIIIXIIXIII",
    "IIIIIIIIXXIXIIIXI",
    "XIXXIIIIIIIIIIXII",
    "IIIIIZIIIZIZZIIII",
    "IIIIIIIIZIZIIZIZI",
    "IIIZIIIZIIIIIIZIZ",
    "IIZIIIZIIIIIIIZIZ",
    "IIIIZZZZZIZZIIIIZ",
    "IZIIZIIIIIZIIZIII",
    "IIIIIIIIZZIZIIIZI",
    "ZIZZIIIIIIIIIIZII"
]

try:
    tableau = stim.Tableau.from_stabilizers([stim.PauliString(s) for s in stabilizers], allow_redundant=True, allow_underconstrained=True)
    circuit = tableau.to_circuit(method="graph_state")
    
    # Post-processing: Replace RX with H
    new_circuit = stim.Circuit()
    for instr in circuit:
        if instr.name == "RX":
            # RX targets are reset to |+>. 
            # If we assume start state is |0>, H takes |0> to |+>.
            # So replace RX q with H q.
            for t in instr.targets_copy():
                new_circuit.append("H", [t])
        elif instr.name == "RY":
             # RY targets are reset to |i+>. 
             # H S S |0> -> H |1> -> |-> ?? No.
             # RY is usually not generated by graph_state for stabilizer states unless complex.
             # Let's assume only RX is common.
             new_circuit.append(instr)
        elif instr.name == "RZ":
             # RZ resets to |0>. This is a reset.
             # If start state is |0>, this is a no-op if we haven't touched the qubit.
             # But graph_state might put it in the middle.
             # If it's at the beginning, we can ignore it.
             # Let's keep it for now and see if evaluate complains about resets.
             new_circuit.append(instr)
        else:
            new_circuit.append(instr)
            
    # Filter out RZ if they are just initialization (at the start)
    # Actually, RZ is "Reset to Z basis", i.e. set to |0>.
    # If the circuit assumes |0> input, RZ is redundant at the start.
    # We can try removing RZ if it appears.
    
    clean_circuit = stim.Circuit()
    for instr in new_circuit:
        if instr.name == "RZ":
             continue # Assume input is |0>
        clean_circuit.append(instr)

    print(clean_circuit)

except Exception as e:
    print(f"Error: {e}")
