import stim

def check_dependence():
    with open('data/gemini-3-pro-preview/agent_files/stabilizers_135.txt', 'r') as f:
        stabs = [line.strip() for line in f if line.strip()]

    # We want to check if any stabilizer is a product of others but with different sign.
    # However, all provided stabilizers have +1 sign (implicitly, as they are just Pauli strings).
    # If a subset of Pauli strings multiplies to Identity, then we have a relation.
    # If they multiply to -Identity, we have a contradiction.
    
    # We can use Gaussian elimination to find dependencies.
    # But stim does this internally.
    
    # Let's try to identify if 44 or 59 are dependent on others.
    # We can check this by seeing if they can be generated by the others.
    
    # Let's verify commutativity again just to be sure.
    
    paulis = [stim.PauliString(s) for s in stabs]
    
    # Indices of interest
    idx_44 = 44
    idx_59 = 59
    idx_119 = 119
    
    print(f"Stab 44: {stabs[44]}")
    print(f"Stab 59: {stabs[59]}")
    print(f"Stab 119: {stabs[119]}")
    
    # Check if 44 commutes with everyone else (except 119)
    for i, p in enumerate(paulis):
        if i == idx_119: continue
        if not paulis[idx_44].commutes(p):
            print(f"Stab 44 anticommutes with Stab {i}")

    # Check if 59 commutes with everyone else (except 119)
    for i, p in enumerate(paulis):
        if i == idx_119: continue
        if not paulis[idx_59].commutes(p):
            print(f"Stab 59 anticommutes with Stab {i}")
            
    # Check if 119 commutes with everyone else (except 44, 59)
    for i, p in enumerate(paulis):
        if i == idx_44 or i == idx_59: continue
        if not paulis[idx_119].commutes(p):
            print(f"Stab 119 anticommutes with Stab {i}")

if __name__ == "__main__":
    check_dependence()
