import stim

def debug_check():
    # Load stabilizers
    with open("stabilizers_95.txt", "r") as f:
        stabs = [line.strip() for line in f if line.strip()]
    
    # Load circuit
    with open("circuit_95_correct.stim", "r") as f:
        circuit_text = f.read()
    circuit = stim.Circuit(circuit_text)
    
    print(f"Loaded circuit with {len(circuit)} instructions")
    
    # Check lengths
    print(f"Number of stabilizers: {len(stabs)}")
    print(f"Length of first stabilizer: {len(stabs[0])}")
    
    # Simulate
    # Start in |0> state
    sim = stim.TableauSimulator()
    sim.do(circuit)
    
    total = 0
    sim.do(circuit)
    
    current_stabs = sim.canonical_stabilizers()
    print(f"Current state has {len(current_stabs)} stabilizers")
    
    # Check if first stabilizer is in the group
    s0 = stim.PauliString(stabs[0])
    print(f"Checking {stabs[0]}")
    # How to check if s0 is in group?
    # We can check if s0 commutes with all generators? Yes.
    # If it commutes with all, but expectation is 0, it means s0 is independent of the group?
    # But the group has 95 generators for 95 qubits. It is a complete basis.
    # So any operator that commutes with all generators MUST be in the group (up to phase).
    # If s0 commutes with all, it is either +1 or -1 * product of generators.
    
    # Print the one that anticommutes
    for idx, gen in enumerate(current_stabs):
        if not s0.commutes(gen):
            print(f"Anticommutes with generator {idx}: {gen}")
            break
    
    val = sim.peek_observable_expectation(s0)
    print(f"Expectation: {val}")
    
    # Check if target stabilizers are in the group generated by current_stabs
    # But checking expectation is enough.
    # If expectation is -1, it means we prepared the -1 eigenstate instead of +1?
    
    preserved = 0
    failed_counts = {1: 0, -1: 0, 0: 0}
    
    for s_str in stabs:
        total += 1
        s = stim.PauliString(s_str)
        val = sim.peek_observable_expectation(s)
        failed_counts[val] += 1
        if val == 1:
            preserved += 1
            
    print(f"Preserved {preserved}/{total}")
    print(f"Expectations: {failed_counts}")

if __name__ == "__main__":
    debug_check()
