import stim

def solve():
    with open("stabilizers_72_fixed.txt", "r") as f:
        stabilizers = [line.strip() for line in f if line.strip()]

    print(f"Loaded {len(stabilizers)} stabilizers.")

    # Convert to stim PauliStrings
    stim_stabilizers = []
    for s in stabilizers:
        stim_stabilizers.append(stim.PauliString(s))

    try:
        # Generate tableau from stabilizers
        # allow_underconstrained=True because we might have fewer than n stabilizers (we have 72 qubits)
        # The prompt lists many stabilizers. Let's see how many.
        # There are lines of text.
        
        tableau = stim.Tableau.from_stabilizers(stim_stabilizers, allow_underconstrained=True)
        
        # Generate circuit
        circuit = tableau.to_circuit("elimination")
        
        print("Circuit generated successfully.")
        
        # Verify locally
        # We check if each generator is stabilized by the tableau
        # A generator G is stabilized if T^-1 * G * T is a product of Zs with +1 phase?
        # No, if T prepares the state from |0>, then T * |0> = |psi>.
        # We need G * |psi> = |psi>.
        # G * T * |0> = T * |0>
        # T^-1 * G * T * |0> = |0>
        # So T^-1 * G * T must be in the stabilizer group of |0>, which is generated by Z_i.
        # So T^-1 * G * T must be a product of Zs (no Xs) and have +1 sign.
        
        inverse_tableau = tableau.inverse()
        all_good = True
        for i, s in enumerate(stim_stabilizers):
            conjugated = inverse_tableau(s)
            
            # Check if it contains only I and Z
            # PauliString representation: xs, zs, sign
            # We want xs to be all False.
            # And sign to be +1 (0).
            
            xs, zs = conjugated.to_numpy()
            if any(xs):
                print(f"Stabilizer {i} failed: Conjugated operator has X components.")
                all_good = False
                break
            
            if conjugated.sign != 1:
                print(f"Stabilizer {i} failed: Conjugated operator has {conjugated.sign} phase.")
                all_good = False
                break
                
        if all_good:
            print("Local verification passed!")
            with open("circuit_72_solution.stim", "w") as f:
                f.write(str(circuit))
        else:
            print("Local verification failed.")

    except Exception as e:
        print(f"Error during generation: {e}")

if __name__ == "__main__":
    solve()
