import stim
import sys

def parse_stabilizers(filename):
    with open(filename, 'r') as f:
        content = f.read()
    
    # Split by comma or newline
    stabs = []
    for part in content.replace('\n', ',').split(','):
        s = part.strip()
        if s:
            stabs.append(stim.PauliString(s))
    return stabs

def count_cx(circuit):
    count = 0
    for instr in circuit:
        if instr.name == "CX" or instr.name == "CNOT":
            count += len(instr.targets_copy()) // 2
    return count

def get_volume(circuit):
    # Volume is total gate count in volume gate set
    # Assuming standard gates in baseline are all volume gates
    count = 0
    for instr in circuit:
        if instr.name in ["CX", "CNOT", "CY", "CZ", "H", "S", "S_DAG", "SQRT_X", "SQRT_X_DAG", "SQRT_Y", "SQRT_Y_DAG"]:
            if instr.name in ["CX", "CNOT", "CY", "CZ"]:
                count += len(instr.targets_copy()) // 2
            else:
                count += len(instr.targets_copy())
    return count

def main():
    stabilizers = parse_stabilizers("data/agent_files/raw_stabilizers.txt")
    print(f"Parsed {len(stabilizers)} stabilizers")
    
    with open("data/agent_files/baseline.stim", "r") as f:
        baseline = stim.Circuit(f.read())
    
    print(f"Baseline CX count: {count_cx(baseline)}")
    print(f"Baseline Volume: {get_volume(baseline)}")
    
    # Check preservation
    # For a stabilizer state, we need to check if the stabilizers are preserved.
    # The baseline should prepare the state from |0>.
    # So we check if Transformed(Stabilizer) * |0> = |0>.
    # Actually, usually we check if the stabilizers stabilize the output state.
    # Since we start with |0>, the stabilizers of the input are Z_i.
    # The output state is U|0>.
    # The stabilizers of the output state are U Z_i U^-1.
    # We want to check if the given stabilizers are in the group generated by U Z_i U^-1.
    # Alternatively, we can check if S_k U |0> = U |0>
    # <=> U^-1 S_k U |0> = |0>
    # <=> U^-1 S_k U stabilizes |0> (i.e., is a product of Zs with +1 phase).
    
    sim = stim.TableauSimulator()
    sim.do(baseline)
    
    # Check if all stabilizers are preserved (have expectation +1)
    all_good = True
    for s in stabilizers:
        if sim.peek_observable_expectation(s) != 1:
            # print(f"Stabilizer {s} NOT preserved")
            all_good = False
            # break
    
    if all_good:
        print("Baseline preserves all stabilizers.")
    else:
        print("Baseline does NOT preserve all stabilizers.")

    # Try synthesis
    try:
        tableau = stim.Tableau.from_stabilizers(stabilizers, allow_underconstrained=True)
        print("Tableau created successfully.")
        
        # Method 1: Graph state
        try:
            circ_graph = tableau.to_circuit(method="graph_state")
            print(f"Graph state synthesis CX count: {count_cx(circ_graph)}")
            print(f"Graph state synthesis Volume: {get_volume(circ_graph)}")
            
            with open("data/agent_files/candidate_graph.stim", "w") as f:
                f.write(str(circ_graph))
                
        except Exception as e:
            print(f"Graph state synthesis failed: {e}")

        # Method 2: Elimination
        try:
            circ_elim = tableau.to_circuit(method="elimination")
            print(f"Elimination synthesis CX count: {count_cx(circ_elim)}")
            print(f"Elimination synthesis Volume: {get_volume(circ_elim)}")
             
            with open("data/agent_files/candidate_elim.stim", "w") as f:
                f.write(str(circ_elim))

        except Exception as e:
            print(f"Elimination synthesis failed: {e}")
            
    except Exception as e:
        print(f"Tableau creation failed: {e}")

if __name__ == "__main__":
    main()
