import stim

def generate():
    # Load stabilizers
    with open('target_stabilizers_task_v2.txt', 'r') as f:
        lines = [line.strip().replace(',', '') for line in f if line.strip()]
    
    # Create tableau
    # allow_underconstrained=True is necessary if the stabilizers don't define a unique state
    # But we want to ensure the specific provided stabilizers are preserved.
    # The resulting tableau will have the provided stabilizers as its stabilizers (or generated by them).
    try:
        tableau = stim.Tableau.from_stabilizers([stim.PauliString(s) for s in lines], allow_underconstrained=True)
    except Exception as e:
        print(f"Error creating tableau: {e}")
        return

    # Synthesize circuit
    # method="graph_state" is usually optimal for CX count (uses CZs)
    circuit = tableau.to_circuit(method="graph_state")
    
    # Save to file
    with open('candidate_graph_v3.stim', 'w') as f:
        f.write(str(circuit))
    
    print("Generated candidate_graph_v3.stim")
    print(f"Gate count: {len(circuit)}")
    
    # Check for CX gates
    cx_count = 0
    cz_count = 0
    for instruction in circuit:
        if instruction.name == "CX" or instruction.name == "CNOT":
            cx_count += len(instruction.targets_copy()) // 2
        elif instruction.name == "CZ":
            cz_count += len(instruction.targets_copy()) // 2
    
    print(f"CX count: {cx_count}")
    print(f"CZ count: {cz_count}")

if __name__ == "__main__":
    generate()
