import stim
import sys

def main():
    # Load stabilizers
    with open("target_stabilizers.txt", "r") as f:
        lines = f.readlines()
    
    # Process lines: remove whitespace/newlines, ignore empty lines
    stabs = []
    for line in lines:
        s = line.strip().replace(" ", "").replace(",", "")
        if s:
            stabs.append(s)

    print(f"Loaded {len(stabs)} stabilizers.")
    
    # Create Tableau
    try:
        pauli_stabs = [stim.PauliString(s.strip()) for s in stabs]
        # allow_underconstrained=True because we might have fewer stabilizers than qubits
        # or we just want to find *a* state that satisfies them.
        tableau = stim.Tableau.from_stabilizers(pauli_stabs, allow_underconstrained=True)
    except Exception as e:
        print(f"Error creating tableau: {e}")
        return

    # Generate Graph State Circuit
    # graph_state synthesis typically prepares the state from |+>^{\otimes n}
    # But let's check what stim does.
    # It returns a circuit that implements the tableau operation.
    # If the tableau T maps Z to S, then T|0> is the state stabilized by S.
    # However, 'graph_state' method specifically decomposes into H, S, CZ, etc.
    # Let's try to generate it.
    
    try:
        cand_graph = tableau.to_circuit(method="graph_state")
    except Exception as e:
        print(f"Error synthesizing graph state: {e}")
        # Fallback to elimination
        print("Falling back to elimination method.")
        cand_graph = tableau.to_circuit(method="elimination")

    # The circuit generated by to_circuit implements the unitary U such that U P U^-1 = P'
    # where P are the Z basis stabilizers and P' are the target stabilizers.
    # So U |0> should be the target state.
    
    # However, sometimes 'graph_state' decomposition results in a circuit that expects |+> input 
    # if it's strictly a graph state construction. 
    # But Stim's to_circuit returns a Clifford circuit that implements the Tableau.
    # So applying it to |0> should work.
    
    # One caveat: The synthesized circuit might contain 'RX', 'RY', 'RZ' or similar resets?
    # No, to_circuit produces unitary gates usually.
    # But let's check if it contains any resets.
    
    # Optimize: Replace CX with CZ is automatic in graph state?
    # Actually graph state uses CZ.
    
    # Save candidate
    with open("candidate.stim", "w") as f:
        f.write(str(cand_graph))
        
    print("Candidate saved to candidate.stim")

    # Local Verification
    print("Checking Candidate...")
    sim = stim.TableauSimulator()
    sim.do(cand_graph)
    
    preserved = 0
    for s in pauli_stabs:
        if sim.peek_observable_expectation(s) == 1:
            preserved += 1
            
    print(f"Candidate locally preserved: {preserved}/{len(pauli_stabs)}")

    # Check Baseline
    print("Checking Baseline...")
    with open("baseline.stim", "r") as f:
        base_circ = stim.Circuit(f.read())
    
    sim_base = stim.TableauSimulator()
    sim_base.do(base_circ)
    
    preserved_base = 0
    negative_base = 0
    zero_base = 0
    
    for i, s in enumerate(pauli_stabs):
        exp = sim_base.peek_observable_expectation(s)
        if exp == 1:
            preserved_base += 1
        elif exp == -1:
            negative_base += 1
            print(f"Stabilizer {i} is -1 in baseline.")
        else:
            zero_base += 1
            print(f"Stabilizer {i} is 0 (indeterminate) in baseline.")
            
    print(f"Baseline: +1: {preserved_base}, -1: {negative_base}, 0: {zero_base}")

if __name__ == "__main__":
    main()
