import stim
import sys

def main():
    try:
        # Load the candidate generated by optimize_circuit.py
        with open("candidate.stim", "r") as f:
            content = f.read()
        
        circuit = stim.Circuit(content)
        new_circuit = stim.Circuit()
        
        # Process operations
        for op in circuit:
            if op.name == "RX":
                # Assuming start in |0>, RX resets to |+>. H transforms |0> to |+>.
                targets = op.targets_copy()
                new_circuit.append("H", targets)
            elif op.name == "R" or op.name == "RZ":
                # Resets to |0>. If at start, identity.
                # If mid-circuit, we can't easily replace without active reset.
                # Stim synthesis puts RZ at start sometimes.
                pass
            elif op.name == "TICK":
                pass
            else:
                new_circuit.append(op)
        
        # Verify with stabilizers
        with open("my_stabilizers.txt", "r") as f:
            lines = [line.strip() for line in f if line.strip()]
        stabilizers = [stim.PauliString(line) for line in lines]
        
        sim = stim.TableauSimulator()
        sim.do(new_circuit)
        
        valid = True
        failed_stab = None
        for i, stab in enumerate(stabilizers):
            if sim.peek_observable_expectation(stab) != 1:
                valid = False
                failed_stab = i
                break
        
        if valid:
            print("VALID: Circuit preserves stabilizers.")
            with open("final_candidate.stim", "w") as f:
                f.write(str(new_circuit))
            print(f"CX count: {sum(len(op.targets_copy())//2 for op in new_circuit if op.name == 'CX')}")
        else:
            print(f"INVALID: Circuit fails stabilizer check at index {failed_stab}.")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
