
import stim
import sys

def count_cx(circuit):
    count = 0
    for op in circuit:
        if op.name in ["CX", "CNOT"]:
            count += len(op.targets_copy()) // 2
    return count

def count_volume(circuit):
    count = 0
    for op in circuit:
        if op.name in ["QUBIT_COORDS", "SHIFT_COORDS", "DETECTOR", "OBSERVABLE_INCLUDE", "TICK"]:
            continue
        targets = op.targets_copy()
        if op.name in ["CX", "CNOT", "CY", "CZ", "SWAP", "ISWAP"]:
            count += len(targets) // 2
        else:
            count += len(targets)
    return count

def get_stabilizers():
    with open(r"C:\Users\anpaz\Repos\quantum-ai\rq3\data\agent_files\target_stabilizers.txt", "r") as f:
        lines = [l.strip() for l in f if l.strip()]
    return [stim.PauliString(l) for l in lines]

def get_baseline():
    with open(r"C:\Users\anpaz\Repos\quantum-ai\rq3\data\agent_files\baseline.stim", "r") as f:
        return stim.Circuit(f.read())

def main():
    try:
        baseline = get_baseline()
        stabilizers = get_stabilizers()
    except Exception as e:
        print(f"Error loading files: {e}")
        return

    cx_base = count_cx(baseline)
    vol_base = count_volume(baseline)
    print(f"Baseline: CX={cx_base}, Vol={vol_base}")

    # Method 1: Gaussian Elimination via Tableau
    try:
        tableau = stim.Tableau.from_stabilizers(stabilizers, allow_underconstrained=True)
        # Note: from_stabilizers might not preserve the sign exactly if underconstrained is True?
        # It finds A state that matches.
        # But we need to preserve the SPECIFIC stabilizers.
        # The prompt says "preserve the same stabilizer behavior".
        # If the target stabilizers are generated by the baseline, then any circuit generating the same stabilizer group is valid.
        
        # Check if tableau is valid (consistent)
        # If it throws, the stabilizers are inconsistent.
        
        cand1 = tableau.to_circuit(method="elimination")
        cx1 = count_cx(cand1)
        vol1 = count_volume(cand1)
        print(f"Candidate 1 (Elimination): CX={cx1}, Vol={vol1}")
        
        best_cand = cand1
        best_cx = cx1
        best_vol = vol1
        
        # Check against baseline
        if cx1 < cx_base or (cx1 == cx_base and vol1 < vol_base):
            print("Candidate 1 is better.")
            with open(r"C:\Users\anpaz\Repos\quantum-ai\rq3\data\agent_files\candidate.stim", "w") as f:
                f.write(str(cand1))
        else:
            print("Candidate 1 is NOT better.")
            # If elimination is worse, maybe the baseline is already quite good or needs local optimization.
            # But I only have 1 attempt for evaluate_optimization.
            # I must be sure.
            
            # Can I improve cand1?
            # stim.Circuit.flattened()
            # Maybe some peephole optimization?
            pass

    except Exception as e:
        print(f"Error in synthesis: {e}")

if __name__ == "__main__":
    main()
