import stim

circuit = stim.Circuit.from_file('input.stim')
sim = stim.TableauSimulator()
sim.do(circuit)

# Get the current stabilizers
# But wait, the circuit has H and CX.
# It starts from |0>.
# So the stabilizers are the Z stabilizers of |0> propagated through the circuit.
# Tableau has .z_output(k) which gives the stabilizer corresponding to Z_k at input?
# No, Z_k at input is stabilizer.
# We want the stabilizers of the state.
# They are the rows of the tableau?
# Tableau stores X_k -> P_k, Z_k -> Q_k.
# The initial stabilizers are Z_0, Z_1, ... Z_{n-1}.
# The final stabilizers are the result of propagating these.
# So for each k, sim.current_tableau().z_output(k) is a stabilizer? No.
# sim.current_tableau() maps input P to output P'.
# Stabilizers of |0> are Z_0, Z_1...
# So their images are Z'_0, Z'_1...
# But wait, if we have H on 0, Z_0 becomes X_0.
# So the stabilizers are the images of Z_k.
# Let's collect them.

tableau = sim.current_inverse_tableau().inverse()
# inverse tableau maps output to input.
# We want forward map?
# Yes, if S_in = Z_k, then S_out = U Z_k U^dag.
# Tableau stores this mapping.
# stim.Tableau.z_output(k) gives the image of Z_k.

stabilizers_circuit = []
num_qubits = circuit.num_qubits
# The prompt stabilizers are length 135.
# The circuit might have fewer qubits used?
# But we should check up to 135.
# If circuit uses fewer, the rest are Z_k (identity operation).
# But prompt stabilizers might be non-trivial on unused qubits?
# Let's generate all 135.

for k in range(135):
    s = tableau.z_output(k)
    stabilizers_circuit.append(s)

print(f"Generated {len(stabilizers_circuit)} stabilizers from circuit.")

# Now load the prompt stabilizers
stabilizers_prompt = []
with open('stabilizers.txt', 'r') as f:
    for line in f:
        if line.strip():
            stabilizers_prompt.append(stim.PauliString(line.strip()))

# Compare
match_count = 0
for s_p in stabilizers_prompt:
    # Check if s_p is in the group generated by stabilizers_circuit
    # But s_p might be a product of generators.
    # However, for graph states, the generators are usually canonical?
    # Or at least we can check if s_p stabilizes the state.
    # The state is stabilized by S if S|psi> = |psi>.
    # We can check this by measuring expectation value?
    # Or using peek_observable_expectation?
    # Or `tableau.peek_z(s_p)`? No.
    # We can check if `s_p` commutes with all stabilizers? No.
    # We can check if `s_p` is in the stabilizer group.
    # Simpler: use `sim.peek_observable_expectation(s_p)`.
    # If +1, it's a stabilizer.
    # If -1, it's -1 stabilizer.
    # If 0, it's not a stabilizer (random outcome).
    
    exp = sim.peek_observable_expectation(s_p)
    if exp == 1:
        match_count += 1
    elif exp == -1:
        print(f"Stabilizer {s_p} has expectation -1!")
    else:
        print(f"Stabilizer {s_p} has expectation 0 (not stabilized).")

print(f"Matched {match_count}/{len(stabilizers_prompt)} prompt stabilizers.")
