import stim

def find_missing():
    # Load circuit
    circuit_str = """H 0 2 4 6 9 11 13 16 18 20 43\nCX 0 2 0 4 0 6 0 9 0 11 0 13 0 16 0 18 0 20 0 21 0 28 0 43\nH 7\nCX 7 0 43 1 1 43 43 1\nH 14\nCX 1 2 1 4 1 6 1 9 1 11 1 13 1 14 1 16 1 18 1 20 1 21 1 45 1 46\nH 42\nCX 42 1 14 2 2 14 14 2 2 21 2 28 2 35 2 45 2 46 7 2 42 2 21 3 3 21 21 3 3 35 28 4 4 28 28 4 4 35 4 45 4 46 7 4 42 4 35 5 5 35 35 5 7 6 6 7 7 6 43 7 7 43 43 7\nH 7 12 19 35\nCX 7 11 7 12 7 18 7 19 7 22 7 28 7 29 7 35 7 42 7 45 7 46 7 48\nH 8\nCX 8 7 42 8 8 42 42 8\nH 15\nCX 8 11 8 12 8 15 8 18 8 19 8 22 8 28 8 35 8 46 8 48 15 9 9 15 15 9 9 22 9 29 9 36 9 45 42 9 22 10 10 22 22 10 10 36 29 11 11 29 29 11 11 36 11 45 42 11 36 12 12 36 36 12 42 13 13 42 42 13 15 14 14 15 15 14 14 16 14 23 14 30 15 14 15 16 15 30 15 46 16 23 16 30 16 37 16 46 23 17 17 23 23 17 17 37 46 18 18 46 46 18 18 30 18 37 31 18 33 18 47 18 48 18 37 19 19 37 37 19 31 19 33 19 47 19 48 19 30 20 20 30 30 20 31 20 33 20 47 20 48 20\nH 21 44\nCX 21 24 21 28 21 29 21 30 21 31 21 35 21 36 21 37 21 42 21 43 21 44 21 46 21 48\nH 22\nCX 22 21 44 22 22 44 44 22\nH 23\nCX 22 23 22 24 22 28 22 29 22 30 22 35 22 36 22 37 22 42 22 43 22 46 22 47 22 48 23 24 23 31 23 38 23 47 44 23 24 38 31 25 25 31 31 25 25 38 25 47 44 25 38 26 26 38 38 26 44 27 27 44 44 27 29 28 28 29 29 28 28 31 28 32 28 46 29 28 29 32 29 45 29 46 29 47 46 30 30 46 46 30 30 31 30 32 30 39 30 45 30 47 31 39 45 32 32 45 45 32 32 39 32 45 32 47 33 32 48 32 39 33 33 39 39 33 39 33 48 33 45 34 34 45 45 34 39 34 48 34 36 35 35 36 36 35 35 37 35 38 35 39 35 48 36 35 36 37 36 39 37 38 37 39 37 40 38 40 39 40 48 39 48 40 48 41 41 48 48 41 42 44 42 45 42 46 43 42 43 45 43 46 43 47 46 44 44 46 46 44 44 45 44 46 44 47 44 48 46 45 45 46 46 45 45 48 47 46 46 47 47 46 46 47 46 48 48 47 47 48 48 47"""
    
    stabilizers_str = """XXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIII, XIXIXIXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIXIXIXIXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIXIXIXIXIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIXIXIXIXIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIXIXIXIXIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXIXIXIXIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXIXIXIX, IIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXI, ZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIII, ZIZIZIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIZIZIZIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIZIZIZIZIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIZIZIZIZIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIZIZIZIZIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZIZIZIZIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZIZIZIZ, IIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIIIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZIIIIIIII, IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZZZZI, IXXIXIIIXXIXIIIIIIIIIIIIIIIIIXXIXIIIXXIXIIIIIIIII, IXXIXIIIIIIIIIIXXIXIIIIIIIIIIXXIXIIIIIIIIIIXXIXII, IIIIIIIIIIIIIIIIIIIIIIXXIXIIIXXIXIIIXXIXIIIXXIXII, IZZIZIIIZZIZIIIIIIIIIIIIIIIIIZZIZIIIZZIZIIIIIIIII, IZZIZIIIIIIIIIIZZIZIIIIIIIIIIZZIZIIIIIIIIIIZZIZII, IIIIIIIIIIIIIIIIIIIIIIZZIZIIIZZIZIIIZZIZIIIZZIZII"""
    
    stabilizers = [s.strip() for s in stabilizers_str.split(',')]
    stim_stabilizers = [stim.PauliString(s) for s in stabilizers]
    
    circuit = stim.Circuit(circuit_str)
    
    # 1. Propagate Z_i from input (Z stabilizers of |0...0>)
    t_total = stim.Tableau.from_circuit(circuit)
    
    propagated_stabilizers = []
    for i in range(49):
        p = stim.PauliString(49)
        p[i] = 2 # Z
        prop = t_total(p)
        propagated_stabilizers.append(prop)
        
    # 2. Check which ones are in the group generated by given stabilizers
    # We can use Tableau to check independence/membership.
    # Create a Tableau from given stabilizers.
    # Check if `prop` commutes with all of them? No.
    # Check if `prop` can be formed by product of them.
    
    # We can assume given stabilizers are independent (49 of them).
    # If independent, they span the full space.
    # So `prop` MUST be in the group.
    # So `prop` * `Inverse(Group)` = Identity.
    
    # Let's just check if `stim_stabilizers` are independent.
    # We can put them in a Tableau and check rank.
    
    # Convert stim_stabilizers to Tableau
    # Stim doesn't have direct "Tableau from stabilizers".
    # But we can assume they are.
    
    # Let's check if `prop` commutes with `stim_stabilizers`.
    # Since both sets stabilize the same state (ideally), they should commute.
    
    commutes_all = True
    for p in propagated_stabilizers:
        for s in stim_stabilizers:
            if not p.commutes(s):
                # print(f"Propagated {p} anticommutes with Given {s}")
                commutes_all = False
                break
    
    if commutes_all:
        print("All propagated stabilizers commute with given stabilizers.")
    else:
        print("WARNING: Propagated stabilizers do NOT commute with given stabilizers!")
        # This implies the circuit prepares a DIFFERENT state than the given stabilizers stabilize.
        # This means the base circuit is WRONG with respect to the given stabilizers?
        # Or my assumption about "stabilizers of |0>" is wrong.
        # "prepares a state that is not necessarily fault-tolerant."
        # It doesn't say "prepares the state stabilized by...".
        # It says "Generate a FT version... that preserves the given stabilizers."
        # This implies the output SHOULD be stabilized by them.
        # If the base circuit prepares something else, then the base circuit is BAD.
        
    # Check if `Q48 X` (from analysis) is a stabilizer
    # We found Expectation 0 in previous analysis.
    # This means `Q48 X` anticommutes with some `prop` stabilizer.
    # Let's find which one.
    
    q48x = stim.PauliString(49)
    q48x[48] = 1 # X
    
    # Propagate Q48 X through circuit?
    # No, Q48 X was a fault at Op 0 (Input).
    # So `q48x` is the fault at input.
    # It anticommutes with Z_48 (at input).
    # Because X_48 and Z_48 anticommute.
    # So `q48x` anticommutes with the stabilizer `Z_48` of the input state.
    # The propagated fault `E_final = U * q48x * U^dag` anticommutes with `U * Z_48 * U^dag`.
    # `U * Z_48 * U^dag` is the propagated stabilizer `propagated_stabilizers[48]`.
    # So `E_final` anticommutes with `propagated_stabilizers[48]`.
    # So `E_final` is DETECTABLE by measuring `propagated_stabilizers[48]`.
    
    # So the only question is: Is `propagated_stabilizers[48]` in the given list?
    # If yes -> Detected.
    # If no -> Undetected (by given list).
    
    # Let's check.
    s_48 = propagated_stabilizers[48]
    print(f"Stabilizer for Q48 X detection: {s_48}")
    
    # Check if s_48 is in given group.
    # We can check if s_48 commutes with all given stabilizers.
    # If it anticommutes with any, it is NOT in the group (and incompatible).
    # If it commutes with all, it MIGHT be in the group.
    
    commutes_with_given = True
    for s in stim_stabilizers:
        if not s_48.commutes(s):
            print(f"s_48 anticommutes with {s}")
            commutes_with_given = False
            break
            
    if commutes_with_given:
        print("s_48 commutes with all given stabilizers. It might be in the group.")
        # But previously my analysis said `Q48 X` commutes with all given stabilizers.
        # We know `Q48 X` anticommutes with `s_48`.
        # If `s_48` is in the group, then `Q48 X` must anticommute with some element of the group.
        # So `Q48 X` cannot commute with all given stabilizers!
        # Contradiction!
        
        # My previous analysis said `Q48 X` (propagated) commutes with all given stabilizers.
        # This implies `s_48` is NOT in the group?
        # If `s_48` is not in the group, but commutes with it.
        # Then `s_48` is a "logical operator" of the code defined by given stabilizers.
        # And `Q48 X` flips its value.
        
        print("Conclusion: s_48 is a logical operator (or missing stabilizer).")
    else:
        print("Conclusion: s_48 is incompatible with given stabilizers.")

if __name__ == "__main__":
    find_missing()
