
import stim

def solve():
    c_str = """
H 0 1 2 3 5 7 9 11
CX 0 1 0 2 0 3 0 5 0 7 0 9 0 11 0 20 0 24 20 1 1 20 20 1 1 14 4 2 2 4 4 2
H 2 6 10
CX 2 6 2 10 2 14 2 22 22 3 3 22 22 3 3 18 8 4 4 8 8 4
H 4
CX 4 18 12 5 5 12 12 5 9 5 8 6 6 8 8 6 6 7 6 9 6 11 6 12 6 14 6 20 6 22 6 24 14 7 7 14 14 7 7 16 8 10 8 16 8 18 18 9 9 18 18 9 18 10 10 18 18 10 20 10 20 11 11 20 20 11 11 15 11 20 11 22 12 14 12 15 12 16 12 24 16 13 13 16 16 13 13 19 18 14 14 18 18 14 14 19 20 15 15 20 20 15 15 16 22 16 16 22 22 16 16 20 16 22 20 17 17 20 20 17 17 20 18 19 18 20 18 24 22 20 20 22 22 20 21 20 22 20 23 20 24 20 22 21 23 21 24 21 23 22 24 22 24 23
"""
    stabs = [
        "XXIIIXXIIIIIIIIIIIIIIIIII", "IIIIIIIIIIXXIIIXXIIIIIIII", "IIIIIIXXIIIXXIIIIIIIIIIII", "IIIIIIIIIIIIIIIIXXIIIXXII", "IIXXIIIXXIIIIIIIIIIIIIIII", "IIIIIIIIIIIIXXIIIXXIIIIII", "IIIIIIIIXXIIIXXIIIIIIIIII", "IIIIIIIIIIIIIIIIIIXXIIIXX", "IIIIXIIIIXIIIIIIIIIIIIIII", "IIIIIXIIIIXIIIIIIIIIIIIII", "IIIIIIIIIIIIIIXIIIIXIIIII", "IIIIIIIIIIIIIIIXIIIIXIIII", "IIIIIZZIIIZZIIIIIIIIIIII", "IIIIIIIIIIIIIIIZZIIIZZIII", "IZZIIIZZIIIIIIIIIIIIIIIII", "IIIIIIIIIIIZZIIIZZIIIIIII", "IIIIIIIZZIIIZZIIIIIIIIIII", "IIIIIIIIIIIIIIIIIZZIIIZZI", "IIIZZIIIZZIIIIIIIIIIIIIII", "IIIIIIIIIIIIIZZIIIZZIIIII", "ZZIIIIIIIIIIIIIIIIIIIIIII", "IIIIIIIIIIIIIIIIIIIIIZZII", "IIZZIIIIIIIIIIIIIIIIIIIII", "IIIIIIIIIIIIIIIIIIIIIIIZZ"
    ]
    # Note: stabs[12] is short in this list (typo in copy). But code logic is generic.
    # Actually, I should use the canonical basis logic properly.
    
    c = stim.Circuit(c_str)
    sim = stim.TableauSimulator()
    sim.do(c)
    
    canonical = sim.canonical_stabilizers()
    
    # We want to print ALL stabilizers generated by the circuit.
    # There are 25.
    # One of them is likely the logical Z.
    # We can just check which one is independent of the 24 given.
    # But actually, I can just include ALL 25 in my check list!
    # If I check all 25, I constrain the state completely.
    # Any deviation (including logical flip) will be detected.
    
    print("Stabilizers from simulation:")
    for s in canonical:
        print(s)

if __name__ == "__main__":
    solve()
