import stim

def check_dependence():
    with open(r"C:\Users\anpaz\Repos\quantum-ai\rq1\data\gemini-3-pro-preview\agent_files\stabilizers_133.txt", "r") as f:
        lines = [line.strip() for line in f if line.strip()]
    
    stabilizers = [stim.PauliString(line) for line in lines]
    
    # Check for dependent stabilizers using Gaussian elimination logic (simulated by Tableau)
    # If we add them one by one, we can see if any contradicts.
    
    t = stim.Tableau(len(stabilizers[0]))
    # We can't easily check for -I dependence using just PauliString methods without implementing Gaussian elimination.
    # But stim.Tableau.from_stabilizers does this.
    
    try:
        t = stim.Tableau.from_stabilizers(stabilizers, allow_redundant=False, allow_underconstrained=True)
        print("Success without redundant.")
    except Exception as e:
        print(f"Error without redundant: {e}")
        
    try:
        t = stim.Tableau.from_stabilizers(stabilizers, allow_redundant=True, allow_underconstrained=True)
        print("Success with redundant.")
        
        # Check specifically for stabilizer 54
        s54 = stabilizers[54]
        # Check if t stabilizes s54
        # Inverse tableau operation on s54
        res = t.peek_z(t.z_output(s54)) # Wait, this is not right.
        # We need to map s54 by the inverse of t.
        # t maps Z_k -> Stabilizer_k.
        # t.inverse() maps Stabilizer_k -> Z_k.
        
        # Let's just create a simulator and measure
        sim = stim.TableauSimulator()
        sim.do_tableau(t.inverse(), [i for i in range(133)])
        # Now the state is |0...0>
        # But wait, t maps |0> to stabilized state.
        # So we want to apply t inverse to the stabilized state?
        # No, simpler: create a state from tableau, measure expectation of s54.
        
        # But simpler logic:
        # Check if s54 is in the stabilizers generated by t.
        pass

    except Exception as e:
        print(f"Error with redundant: {e}")

if __name__ == "__main__":
    check_dependence()
