import stim

def check_signs():
    with open(r'C:\Users\anpaz\Repos\quantum-ai\rq1\data\gemini-3-pro-preview\agent_files\stabilizers_81_qubits.txt', 'r') as f:
        lines = [line.strip() for line in f if line.strip()]

    stabilizers = [stim.PauliString(s) for s in lines]
    
    # Re-create the tableau exactly as I did before
    tableau = stim.Tableau.from_stabilizers(
        stabilizers, 
        allow_underconstrained=True,
        allow_redundant=True
    )
    
    # Check expectation values
    # For a stabilizer state, expectation of any Pauli P is +1, -1, or 0.
    # If P is in the stabilizer group, it's +1 or -1.
    
    failed_indices = []
    for i, s in enumerate(stabilizers):
        # We can check by measuring the observable on the tableau.
        # But `peek_observable_expectation` is not available in all versions.
        # Instead, we can use `tableau.inverse()` to map the Pauli to the Z basis and see if it's +Z or -Z.
        # Or simpler:
        # Just check if 's' or '-s' is in the stabilizer group generated by the tableau.
        # Actually tableau stores generators.
        pass

    # Let's just simulate the circuit and measure the stabilizers.
    circuit = tableau.to_circuit("elimination")
    
    # Add measurements for each stabilizer
    # We can measure a Pauli string by:
    # 1. Change basis (H for X, S dag H for Y)
    # 2. Measure Zs
    # 3. Parity
    # But that's complicated to implement correctly for 80 stabilizers.
    
    # Easier: use TableauSimulator
    sim = stim.TableauSimulator()
    sim.do(circuit)
    
    for i, s in enumerate(stabilizers):
        expectation = sim.peek_observable_expectation(s)
        if expectation != 1:
            print(f"Stabilizer {i} expectation: {expectation}")
            print(f"String: {s}")

if __name__ == "__main__":
    check_signs()
