import sys
import stim
import traceback
import json
import os

base_dir = r"C:\Users\anpaz\Repos\quantum-ai\rq1"

def fix_circuit(filename):
    with open(filename, 'r') as f:
        lines = [l.strip() for l in f if l.strip()]
    
    # Identify the failing stabilizer
    failing_stab_str = "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIXXXXXXIII"
    
    try:
        # Convert strings to PauliStrings
        pauli_stabilizers = [stim.PauliString(s) for s in lines]
        
        # Create a tableau from the stabilizers
        t = stim.Tableau.from_stabilizers(pauli_stabilizers, allow_redundant=True, allow_underconstrained=True)
        
        # Check the sign of the failing stabilizer
        failing_stab = stim.PauliString(failing_stab_str)
        
        # We can check if the tableau satisfies the stabilizer
        # Or rather, we want to find a state that satisfies ALL.
        # If `from_stabilizers` succeeded, there EXISTS a state.
        # But `to_circuit()` might prepare a state where the unconstrained degrees of freedom 
        # are set to +Z (0 state).
        # If the failing stabilizer is NOT in the group generated by the others, 
        # but IS compatible, then `from_stabilizers` should have included it.
        
        # If the stabilizer IS in the group, but `check_stabilizers_tool` says it failed,
        # then either `stim` thinks it's satisfied (so +1) and the tool is wrong,
        # OR `stim` found it's -1? But `from_stabilizers` ensures +1 for all inputs.
        
        # Let's verify if `t` satisfies `failing_stab`.
        # t( |0> ) is the state.
        # We check if failing_stab * t(|0>) = t(|0>).
        # Equivalently, check if t_inv * failing_stab * t stabilizes |0>.
        # i.e. is it a product of Zs?
        
        # Actually, let's just force the sign flip if needed.
        # If the circuit prepares a state where S = -1, we can apply an operation that flips S 
        # but commutes with others?
        # If S is independent, we can fix it.
        # If S is dependent, then S must be +1 if the others are +1 (if consistent).
        
        print("Checking consistency...")
        # Re-create without allow_underconstrained to check consistency/independence?
        # t_strict = stim.Tableau.from_stabilizers(pauli_stabilizers, allow_redundant=True)
        # If this fails, they are inconsistent.
        
        # Let's try to add the failing stabilizer explicitly if it was missed?
        # No, it's in the list.
        
        # Maybe the `check_stabilizers_tool` output `false` means it was NOT satisfied.
        # This implies `stim` generated a circuit where it is -1.
        # This is only possible if `stim` thought it was redundant but with a different sign?
        # But `from_stabilizers` throws error on inconsistency.
        
        # Let's try to verify with Python script if the circuit satisfies the stabilizer.
        c = t.to_circuit()
        sim = stim.TableauSimulator()
        sim.do(c)
        
        is_sat = sim.measure_observable(failing_stab)
        # measure_observable returns the measurement result. 
        # If it's a stabilizer, the result is deterministic.
        # If result is False (0), it's +1 eigenstate.
        # If result is True (1), it's -1 eigenstate.
        
        print(f"Simulator check for {failing_stab_str}: {is_sat}")
        
        if is_sat: # Means -1
            print("Circuit prepares -1 eigenstate! Attempting to fix...")
            # If it's -1, and it WAS in the input list, that's a Stim bug or I'm misunderstanding.
            # UNLESS allow_underconstrained=True ignored the sign of redundant generators?
            # No, it checks consistency.
            
            # Maybe it's NOT redundant, but `allow_underconstrained` didn't enforce it?
            # Wait, `from_stabilizers` takes the list and enforces them.
            
            pass
        else:
            print("Circuit prepares +1 eigenstate according to local sim.")
            
    except Exception as e:
        print(f"Error: {e}")
        traceback.print_exc()

if __name__ == "__main__":
    fix_circuit(os.path.join(base_dir, "data", "gemini-3-pro-preview", "agent_files", "stabilizers_81_v2.txt"))
