import stim
import sys
import os

def solve_with_sim(stabilizers_file, output_file):
    with open(stabilizers_file, 'r') as f:
        lines = [line.strip().replace(',', '') for line in f.readlines() if line.strip()]
    
    stabilizers = []
    for s in lines:
        if len(s) < 171: s += 'I' * (171 - len(s))
        elif len(s) > 171: s = s[:171]
        stabilizers.append(stim.PauliString(s))
        
    print(f"Loaded {len(stabilizers)} base stabilizers.")
    
    # Use TableauSimulator to find the stabilizer group
    # We want a state stabilized by 'stabilizers'.
    # We can try to prepare it by measuring the stabilizers.
    # If we measure them all, we project into the subspace.
    # Then the state is a stabilizer state.
    # We can ask Stim for the canonical stabilizers of that state!
    
    sim = stim.TableauSimulator()
    # Start with |0...0>
    sim.do(stim.Circuit(f"R 0 {170}"))
    
    # Measure each base stabilizer
    # We don't care about the outcome, but we want to force it to be compatible?
    # No, we just measure. The state collapses.
    # If the measurement outcome is -1, then the state is stabilized by -S.
    # We want +S.
    # But for now, let's just find ANY set of stabilizers (signs don't matter for the structure).
    # Once we have the full set of 171 stabilizers (canonical), we can fix the signs.
    
    # BUT: The base stabilizers might NOT be compatible with each other?
    # We checked commutativity, they commute.
    # So we can measure them sequentially.
    
    print("Measuring base stabilizers...")
    for i, s in enumerate(stabilizers):
        sim.measure_observable(s)
        
    # Now the state is stabilized by +/- S_i for all i.
    # And it's a pure state on 171 qubits.
    # So it has 171 canonical stabilizers.
    
    print("Extracting canonical stabilizers...")
    canonical = sim.canonical_stabilizers()
    print(f"Found {len(canonical)} canonical stabilizers.")
    
    # Now we have a full set of 171 stabilizers.
    # But some might have -1 sign (because of random measurement outcomes).
    # And the base stabilizers we want must have +1.
    
    # We need to correct the signs.
    # However, we can't just flip signs in the tableau arbitrarily if they are generated by measurements.
    # But we can construct a circuit that prepares this state.
    # Tableau.from_stabilizers(canonical) gives a tableau T.
    # T|0> = |psi>.
    # |psi> is stabilized by canonical[j].
    
    # We want a state stabilized by +S_base.
    # Let's check which signs we got.
    
    # We can build a Tableau from the canonical stabilizers (ignoring signs for a moment, or using them).
    # Then we check the signs of S_base on this state.
    # If S_base[i] has -1, we need to apply a correction that flips S_base[i] but commutes with others?
    # Or simpler:
    # We have a full set of 171 independent commuting Pauli strings (the Pauli parts of canonical).
    # Let's call them G_1, ..., G_171.
    # The group generated by G includes +/- S_base.
    # We want to find a set of generators G' such that S_base are in the group with +1 sign.
    
    # Actually, if we use `Tableau.from_stabilizers(canonical)`, we get a circuit.
    # This circuit prepares a state |phi>.
    # |phi> satisfies +/- S_base.
    # We can just check the signs.
    
    tableau = stim.Tableau.from_stabilizers(canonical)
    circuit = tableau.to_circuit(method="elimination")
    
    # Write to file
    with open(output_file, "w") as f:
        f.write(str(circuit))
    print(f"Circuit written to {output_file}")
    
    # Now we need to correct the signs.
    # We can use `check_stabilizers_tool` to see which ones are wrong?
    # Or check locally.
    
    # The `check_stabilizers_tool` will tell us which stabilizers are preserved (+1).
    # If we get -1, we might need to apply X/Z gates to flip them.
    # But applying X/Z might flip other stabilizers.
    # We need to find corrections.
    
    # But first, let's see if we get a valid circuit structure.
    
if __name__ == "__main__":
    stabilizers_file = r"C:\Users\anpaz\Repos\quantum-ai\rq1\data\gemini-3-pro-preview\agent_files\stabilizers_171.txt"
    output_file = r"C:\Users\anpaz\Repos\quantum-ai\rq1\data\gemini-3-pro-preview\agent_files\circuit_171.stim"
    solve_with_sim(stabilizers_file, output_file)
