import stim
import sys

def verify_full():
    print("Loading stabilizers...")
    with open("data/gemini-3-pro-preview/agent_files/stabilizers_133.txt", "r") as f:
        stabilizers = [line.strip() for line in f if line.strip()]

    print("Loading circuit...")
    with open("data/gemini-3-pro-preview/agent_files/circuit_133_cleaned.stim", "r") as f:
        circuit_text = f.read()

    print("Parsing circuit...")
    c = stim.Circuit(circuit_text)
    
    print("Converting circuit to tableau...")
    # We need to simulate the circuit to get the final tableau
    # Start with identity tableau
    t = stim.Tableau(133)
    # Apply circuit
    for instr in c:
        if instr.name == "H":
            for t_idx in instr.targets_copy():
                t.h(t_idx.value)
        elif instr.name == "CX":
            targets = instr.targets_copy()
            for i in range(0, len(targets), 2):
                t.cx(targets[i].value, targets[i+1].value)
        else:
            print(f"Unknown instruction: {instr.name}")
            return

    # Check if stabilizers are preserved
    # For each stabilizer S, we want T * S_input * T_inv = S? 
    # No. The circuit prepares the state |psi> = U |0>.
    # We want S |psi> = |psi>.
    # So S U |0> = U |0>  =>  (U_dag S U) |0> = |0>.
    # So if we conjugate the stabilizer by the inverse of the circuit, we should get a Z-type Pauli (or I) that acts on qubits that are in |0> state?
    # Stim's Tableau class stores the mapping of Pauli generators.
    # actually, t(P) gives U P U_dag.
    # So we want U P U_dag to be a stabilizer of |0>.
    # The stabilizers of |0> are Z0, Z1, ...
    # So we want U_dag S U to be in the group generated by {Z0, ..., Zn}.
    # Wait, t.inverse() gives U_dag.
    # Let's use tableau simulation.
    
    sim = stim.TableauSimulator()
    sim.do(c)
    
    # Check each stabilizer
    all_good = True
    for i, s_str in enumerate(stabilizers):
        p = stim.PauliString(s_str)
        expectation = sim.peek_observable_expectation(p)
        if expectation != 1:
            print(f"Stabilizer {i} NOT preserved. Expectation: {expectation}")
            all_good = False
            # break
    
    if all_good:
        print("ALL STABILIZERS PRESERVED locally!")
    else:
        print("Some stabilizers failed.")

if __name__ == "__main__":
    verify_full()
